version: "3.6"
services:
  postgres:
    image: postgres
    container_name: postgres${DOCKER_ID}
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - debridge-node-network
  ipfs-daemon:
    build: ./ipfs-daemon
    container_name: ipfs-daemon${DOCKER_ID}
    command: daemon --writable --enable-pubsub-experiment
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
    networks:
      - debridge-node-network
networks:
  debridge-node-network:
    name: debridge-node-network
secrets:
  keystore:
    file: ./secrets/keystore.json
