apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXN0ZXN0cGFzc3dvcmQ=
  API_PASSWORD: cG9zdGdyZXN0ZXN0cGFzc3dvcmQ=
  KEYSTORE_PASSWORD: TzBld2JTWU5uZ1dwMEVCaXFxM25LazY5dUJOaVRPdFNkMWxsT0daZA==
  JWT_SECRET: Rk5Kamtuc2pzbmZuc2Zqc2tqbmYK
  DEBRIDGE_API_ACCESS_KEY: OGE0YjhhMWItODJlOS00NDk3LWIyZDItNjhiNDQ3YWE5YzE0Cg==
  keystore.json: eyJ2ZXJzaW9uIjozLCJpZCI6IjRkMWUzZDhjLWQ1MmEtNGRkYS1hYWU0LWM2OWRlNTllODNmMCIsImFkZHJlc3MiOiI3ZGQ4Mjc2N2NmNjVhYzIxNjI5MjhmN2JjODQ2M2ZhOTA4NGQ5ZDNlIiwiY3J5cHRvIjp7ImNpcGhlcnRleHQiOiI5N2Q1ZGQzYTliMDk4NmFjMDI1OWFmMDIwZjQxOThkMzhmMjI0ZWYwZjJkOTk0Nzc5YWU4ZDExMzJmY2Y2ZTc0IiwiY2lwaGVycGFyYW1zIjp7Iml2IjoiYzhmYmQ0NjBiMWMxZGYxMzMwNGZjOTNhMWFiODg1ZTQifSwiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJrZGYiOiJzY3J5cHQiLCJrZGZwYXJhbXMiOnsiZGtsZW4iOjMyLCJzYWx0IjoiMTViZWEyZGJlY2I3Mzc1NmVjYzE0MjlmOTE4ZmMyYzAyMmVkYTgyYzdiODRmMTU2YWVkYzM0YTg1YThiMjg5MSIsIm4iOjgxOTIsInIiOjgsInAiOjF9LCJtYWMiOiJhZDFjYzhmNGU0OWY3NmIwZmQ4ZjQxM2FmZTNjODZkN2UxMTgyMjQ0ODhiYTNkYTFhNjk0ZGU4N2NlNDJlZjU1In19
  ORBITDB_PASSWORD: cGFzc3dvcmQK
  ORBITDB_JWT_SECRET: anNuZmtmanNua2ZqbmtzZgo=
