apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Gi
  hostPath:
    path: /opt/k8s/pgdata

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-daemon
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /opt/k8s/ipfs-daemon

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbitdb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  hostPath:
    path: /opt/k8s/orbitdb
