apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-03113349e923cf8f7
